config/routes.rb
Rails.application.routes.draw do
  resources :operations
  resources :privileges
  resources :authorizations
  resources :role_permissions
  resources :user_roles
  resources :identifications
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  resources :roles
  resources :permissions
  resources :identification_types
  resources :resources
  get "main/index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"

  root "main#index";

end

app/models/role_permission.rb
# == Schema Information
#
# Table name: role_permissions
#
#  id            :bigint           not null, primary key
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  permission_id :bigint           not null
#  role_id       :bigint           not null
#
# Indexes
#
#  index_role_permissions_on_permission_id  (permission_id)
#  index_role_permissions_on_role_id        (role_id)
#
# Foreign Keys
#
#  fk_rails_...  (permission_id => permissions.id)
#  fk_rails_...  (role_id => roles.id)
#
class RolePermission < ApplicationRecord
  belongs_to :role
  belongs_to :permission
end

app/controllers/role_permissions_controller.rb
class RolePermissionsController < ApplicationController
  before_action :set_role_permission, only: %i[ show edit update destroy ]

  # GET /role_permissions or /role_permissions.json
  def index
    @role_permissions = RolePermission.all
  end

  # GET /role_permissions/1 or /role_permissions/1.json
  def show
  end

  # GET /role_permissions/new
  def new
    @role_permission = RolePermission.new
  end

  # GET /role_permissions/1/edit
  def edit
  end

  # POST /role_permissions or /role_permissions.json
  def create
    @role_permission = RolePermission.new(role_permission_params)

    respond_to do |format|
      if @role_permission.save
        format.html { redirect_to @role_permission, notice: "Role permission was successfully created." }
        format.json { render :show, status: :created, location: @role_permission }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @role_permission.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /role_permissions/1 or /role_permissions/1.json
  def update
    respond_to do |format|
      if @role_permission.update(role_permission_params)
        format.html { redirect_to @role_permission, notice: "Role permission was successfully updated." }
        format.json { render :show, status: :ok, location: @role_permission }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @role_permission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /role_permissions/1 or /role_permissions/1.json
  def destroy
    @role_permission.destroy!

    respond_to do |format|
      format.html { redirect_to role_permissions_path, status: :see_other, notice: "Role permission was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_role_permission
      @role_permission = RolePermission.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def role_permission_params
      params.expect(role_permission: [ :role_id, :permission_id ])
    end
end

app/helpers/role_permissions_helper.rb
module RolePermissionsHelper
end

app/views/role_permissions/_form.html.erb
<%= form_with(model: role_permission, class: "contents") do |form| %>
  <% if role_permission.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(role_permission.errors.count, "error") %> prohibited this role_permission from being saved:</h2>

      <ul class="list-disc ml-6">
        <% role_permission.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :role_id %>
    <%= form.text_field :role_id, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": role_permission.errors[:role_id].none?, "border-red-400 focus:outline-red-600": role_permission.errors[:role_id].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :permission_id %>
    <%= form.text_field :permission_id, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": role_permission.errors[:permission_id].none?, "border-red-400 focus:outline-red-600": role_permission.errors[:permission_id].any?}] %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/role_permissions/_role_permission.html.erb
<div id="<%= dom_id role_permission %>" class="my-5 space-y-5">
  <div>
    <strong class="block font-medium mb-1">Role:</strong>
    <%= role_permission.role_id %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Permission:</strong>
    <%= role_permission.permission_id %>
  </div>
</div>

app/views/role_permissions/edit.html.erb
<% content_for :title, "Editing role permission" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing role permission</h1>

  <%= render "form", role_permission: @role_permission %>

  <%= link_to "Show this role permission", @role_permission, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to role permissions", role_permissions_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/role_permissions/index.html.erb
<% content_for :title, "Role permissions" %>

<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Role permissions</h1>
    <%= link_to "New role permission", new_role_permission_path, class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
  </div>

  <div id="role_permissions" class="min-w-full divide-y divide-gray-200 space-y-5">
    <% if @role_permissions.any? %>
      <% @role_permissions.each do |role_permission| %>
        <div class="flex justify-between items-center">
          <%= render role_permission %>
          <div class="space-x-2">
            <%= link_to "Show", role_permission, class: "rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= link_to "Edit", edit_role_permission_path(role_permission), class: "rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <div class="inline-block">
              <%= button_to "Destroy", role_permission, method: :delete, class: "rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
            </div>
          </div>
        </div>
      <% end %>
    <% else %>
      <p class="text-center my-10">No role permissions found.</p>
    <% end %>
  </div>
</div>

app/views/role_permissions/new.html.erb
<% content_for :title, "New role permission" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New role permission</h1>

  <%= render "form", role_permission: @role_permission %>

  <%= link_to "Back to role permissions", role_permissions_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/role_permissions/show.html.erb
<% content_for :title, "Showing role permission" %>

<div class="md:w-2/3 w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl">Showing role permission</h1>

  <%= render @role_permission %>

  <%= link_to "Edit this role permission", edit_role_permission_path(@role_permission), class: "mt-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to role permissions", role_permissions_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <div class="inline-block ml-2">
    <%= button_to "Destroy this role permission", @role_permission, method: :delete, class: "mt-2 rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
  </div>
</div>