config/routes.rb
Rails.application.routes.draw do
  resources :operations
  resources :privileges
  resources :authorizations
  resources :role_permissions
  resources :user_roles
  resources :identifications
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  resources :roles
  resources :permissions
  resources :identification_types
  resources :resources
  get "main/index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"

  root "main#index";

end

app/views/resources/_form.html.erb
<%= form_with(model: resource, class: "contents") do |form| %>
  <% if resource.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

      <ul class="list-disc ml-6">
        <% resource.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": resource.errors[:name].none?, "border-red-400 focus:outline-red-600": resource.errors[:name].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :entity_type %>
    <%= form.text_field :entity_type, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": resource.errors[:entity_type].none?, "border-red-400 focus:outline-red-600": resource.errors[:entity_type].any?}] %>
  </div>

  <div class="my-5 flex items-center gap-2">
    <%= form.label :is_visible %>
    <%= form.checkbox :is_visible, class: ["block shadow-sm rounded-md border order-first h-5 w-5", {"border-gray-400 focus:outline-blue-600": resource.errors[:is_visible].none?, "border-red-400 focus:outline-red-600": resource.errors[:is_visible].any?}] %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/resources/_resource.html.erb
<div id="<%= dom_id resource %>" class="my-5 space-y-5">
  <div>
    <strong class="block font-medium mb-1">Name:</strong>
    <%= resource.name %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Entity type:</strong>
    <%= resource.entity_type %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Is visible:</strong>
    <%= resource.is_visible? ? "Yes" : "No" %>
  </div>
</div>

app/views/resources/edit.html.erb
<% content_for :title, "Editing resource" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing resource</h1>

  <%= render "form", resource: @resource %>

  <%= link_to "Show this resource", @resource, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to resources", resources_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/resources/index.html.erb
<% content_for :title, "Resources" %>

<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Recursos</h1>
    <%= link_to "Nuevo recurso", new_resource_path, class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
  </div>

 

<div class="overflow-x-auto pt-20">
  <table class="table table-zebra">
    <!-- head -->
    <thead>
      <tr>
        <th>ID</th>
        <th>Nombre</th>
        <th>Entidad</th>
        <th>es visible ?</th>
        <th>Accion</th>
      </tr>
    </thead>
    <tbody>

      <% @resources.each do |resource| %>

        <tr>
        <th><%= resource.id %></th>
        <th><%= resource.name %></th>
        <th><%= resource.entity_type %></th>
        <th><%= resource.is_visible %></th>

            <% if @resources.any? %>
        <th>
          <div class="join">

          <%= link_to "Ver", resource, class: "btn join-item " %>
          <%= link_to "Editar", edit_resource_path(resource), class: "btn join-item "%>
          <div class="inline-block">
            <%= button_to "Eliminar", resource, method: :delete, class: "btn join-item btn-error", data: { turbo_confirm: "Are you sure?" } %>
          </div>
          
          </div>
        
        </th>
        <% else %>
              <p class="text-center my-10">No se encontraron registros</p>
            <%end%>


      </tr>
      <% end %>
    

    </tbody>
  </table>
</div>

app/views/resources/new.html.erb
<% content_for :title, "New resource" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New resource</h1>

  <%= render "form", resource: @resource %>

  <%= link_to "Back to resources", resources_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/resources/show.html.erb
<% content_for :title, "Showing resource" %>

<div class="md:w-2/3 w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl">Showing resource</h1>

  <%= render @resource %>

  <%= link_to "Edit this resource", edit_resource_path(@resource), class: "mt-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to resources", resources_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <div class="inline-block ml-2">
    <%= button_to "Destroy this resource", @resource, method: :delete, class: "mt-2 rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
  </div>
</div>