config/routes.rb
Rails.application.routes.draw do
  resources :operations
  resources :privileges
  resources :authorizations
  resources :role_permissions
  resources :user_roles
  resources :identifications
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  resources :roles
  resources :permissions
  resources :identification_types
  resources :resources
  get "main/index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"

  root "main#index";

end

app/models/authorization.rb
# == Schema Information
#
# Table name: authorizations
#
#  id           :bigint           not null, primary key
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  operation_id :bigint           not null
#  resource_id  :bigint           not null
#  user_id      :bigint           not null
#
# Indexes
#
#  index_authorizations_on_operation_id  (operation_id)
#  index_authorizations_on_resource_id   (resource_id)
#  index_authorizations_on_user_id       (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (operation_id => operations.id)
#  fk_rails_...  (resource_id => resources.id)
#  fk_rails_...  (user_id => users.id)
#
class Authorization < ApplicationRecord
  belongs_to :user
  belongs_to :operation
  belongs_to :resource
end

app/controllers/authorizations_controller.rb
class AuthorizationsController < ApplicationController
  before_action :set_authorization, only: %i[ show edit update destroy ]

  # GET /authorizations or /authorizations.json
  def index
    @authorizations = Authorization.all
  end

  # GET /authorizations/1 or /authorizations/1.json
  def show
  end

  # GET /authorizations/new
  def new
    @authorization = Authorization.new
  end

  # GET /authorizations/1/edit
  def edit
  end

  # POST /authorizations or /authorizations.json
  def create
    @authorization = Authorization.new(authorization_params)

    respond_to do |format|
      if @authorization.save
        format.html { redirect_to @authorization, notice: "Authorization was successfully created." }
        format.json { render :show, status: :created, location: @authorization }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @authorization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authorizations/1 or /authorizations/1.json
  def update
    respond_to do |format|
      if @authorization.update(authorization_params)
        format.html { redirect_to @authorization, notice: "Authorization was successfully updated." }
        format.json { render :show, status: :ok, location: @authorization }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @authorization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authorizations/1 or /authorizations/1.json
  def destroy
    @authorization.destroy!

    respond_to do |format|
      format.html { redirect_to authorizations_path, status: :see_other, notice: "Authorization was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_authorization
      @authorization = Authorization.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def authorization_params
      params.expect(authorization: [ :user_id, :operation_id, :resource_id ])
    end
end

app/helpers/authorizations_helper.rb
module AuthorizationsHelper
end

app/views/authorizations/_authorization.html.erb
<div id="<%= dom_id authorization %>" class="my-5 space-y-5">
  <div>
    <strong class="block font-medium mb-1">User:</strong>
    <%= authorization.user_id %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Operation:</strong>
    <%= authorization.operation_id %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Resource:</strong>
    <%= authorization.resource_id %>
  </div>
</div>

app/views/authorizations/_form.html.erb
<%= form_with(model: authorization, class: "contents") do |form| %>
  <% if authorization.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(authorization.errors.count, "error") %> prohibited this authorization from being saved:</h2>

      <ul class="list-disc ml-6">
        <% authorization.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": authorization.errors[:user_id].none?, "border-red-400 focus:outline-red-600": authorization.errors[:user_id].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :operation_id %>
    <%= form.text_field :operation_id, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": authorization.errors[:operation_id].none?, "border-red-400 focus:outline-red-600": authorization.errors[:operation_id].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :resource_id %>
    <%= form.text_field :resource_id, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": authorization.errors[:resource_id].none?, "border-red-400 focus:outline-red-600": authorization.errors[:resource_id].any?}] %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/authorizations/edit.html.erb
<% content_for :title, "Editing authorization" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing authorization</h1>

  <%= render "form", authorization: @authorization %>

  <%= link_to "Show this authorization", @authorization, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to authorizations", authorizations_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/authorizations/index.html.erb
<% content_for :title, "Authorizations" %>

<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Authorizations</h1>
    <%= link_to "New authorization", new_authorization_path, class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
  </div>

  <div id="authorizations" class="min-w-full divide-y divide-gray-200 space-y-5">
    <% if @authorizations.any? %>
      <% @authorizations.each do |authorization| %>
        <div class="flex justify-between items-center">
          <%= render authorization %>
          <div class="space-x-2">
            <%= link_to "Show", authorization, class: "rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= link_to "Edit", edit_authorization_path(authorization), class: "rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <div class="inline-block">
              <%= button_to "Destroy", authorization, method: :delete, class: "rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
            </div>
          </div>
        </div>
      <% end %>
    <% else %>
      <p class="text-center my-10">No authorizations found.</p>
    <% end %>
  </div>
</div>

app/views/authorizations/new.html.erb
<% content_for :title, "New authorization" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New authorization</h1>

  <%= render "form", authorization: @authorization %>

  <%= link_to "Back to authorizations", authorizations_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/authorizations/show.html.erb
<% content_for :title, "Showing authorization" %>

<div class="md:w-2/3 w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl">Showing authorization</h1>

  <%= render @authorization %>

  <%= link_to "Edit this authorization", edit_authorization_path(@authorization), class: "mt-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to authorizations", authorizations_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <div class="inline-block ml-2">
    <%= button_to "Destroy this authorization", @authorization, method: :delete, class: "mt-2 rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
  </div>
</div>