config/routes.rb
Rails.application.routes.draw do
  resources :operations
  resources :privileges
  resources :authorizations
  resources :role_permissions
  resources :user_roles
  resources :identifications
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  resources :roles
  resources :permissions
  resources :identification_types
  resources :resources
  get "main/index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"

  root "main#index";

end

app/models/identification.rb
# == Schema Information
#
# Table name: identifications
#
#  id                     :bigint           not null, primary key
#  number                 :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  identification_type_id :bigint           not null
#  user_id                :bigint           not null
#
# Indexes
#
#  index_identifications_on_identification_type_id  (identification_type_id)
#  index_identifications_on_user_id                 (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (identification_type_id => identification_types.id)
#  fk_rails_...  (user_id => users.id)
#
class Identification < ApplicationRecord
  belongs_to :user
  belongs_to :identification_type

  # Validations
  validates :number, presence: true, uniqueness: true
  validates :user_id, presence: true
  validates :identification_type_id, presence: true, uniqueness: { scope: :user_id }
end

app/models/identification_type.rb
# == Schema Information
#
# Table name: identification_types
#
#  id           :bigint           not null, primary key
#  abbreviation :string
#  description  :text
#  name         :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
# Indexes
#
#  index_identification_types_on_name  (name) UNIQUE
#
class IdentificationType < ApplicationRecord
  # Validations
  validates :name, presence: true, uniqueness: true
  validates :abbreviation, presence: true, uniqueness: true
  # validates :description, presence: true

  # Associations
  has_many :identifications, dependent: :destroy
  has_many :users, through: :identifications

  # Scopes
  # scope :ordered_by_name, -> { order(:name) }
end

app/controllers/identifications_controller.rb
class IdentificationsController < ApplicationController
  before_action :set_identification, only: %i[ show edit update destroy ]

  # GET /identifications or /identifications.json
  def index
    @identifications = Identification.all
  end

  # GET /identifications/1 or /identifications/1.json
  def show
  end

  # GET /identifications/new
  def new
    @identification = Identification.new
  end

  # GET /identifications/1/edit
  def edit
  end

  # POST /identifications or /identifications.json
  def create
    @identification = Identification.new(identification_params)

    respond_to do |format|
      if @identification.save
        format.html { redirect_to @identification, notice: "Identification was successfully created." }
        format.json { render :show, status: :created, location: @identification }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @identification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /identifications/1 or /identifications/1.json
  def update
    respond_to do |format|
      if @identification.update(identification_params)
        format.html { redirect_to @identification, notice: "Identification was successfully updated." }
        format.json { render :show, status: :ok, location: @identification }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @identification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /identifications/1 or /identifications/1.json
  def destroy
    @identification.destroy!

    respond_to do |format|
      format.html { redirect_to identifications_path, status: :see_other, notice: "Identification was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_identification
      @identification = Identification.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def identification_params
      params.expect(identification: [ :user_id, :identification_type_id, :number ])
    end
end

app/helpers/identifications_helper.rb
module IdentificationsHelper
end

app/views/identifications/_form.html.erb
<%= form_with(model: identification, class: "contents") do |form| %>
  <% if identification.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(identification.errors.count, "error") %> prohibited this identification from being saved:</h2>

      <ul class="list-disc ml-6">
        <% identification.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": identification.errors[:user_id].none?, "border-red-400 focus:outline-red-600": identification.errors[:user_id].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :identification_type_id %>
    <%= form.text_field :identification_type_id, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": identification.errors[:identification_type_id].none?, "border-red-400 focus:outline-red-600": identification.errors[:identification_type_id].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :number %>
    <%= form.text_field :number, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": identification.errors[:number].none?, "border-red-400 focus:outline-red-600": identification.errors[:number].any?}] %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/identifications/_identification.html.erb
<div id="<%= dom_id identification %>" class="my-5 space-y-5">
  <div>
    <strong class="block font-medium mb-1">User:</strong>
    <%= identification.user_id %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Identification type:</strong>
    <%= identification.identification_type_id %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Number:</strong>
    <%= identification.number %>
  </div>
</div>

app/views/identifications/edit.html.erb
<% content_for :title, "Editing identification" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing identification</h1>

  <%= render "form", identification: @identification %>

  <%= link_to "Show this identification", @identification, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to identifications", identifications_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/identifications/index.html.erb
<% content_for :title, "Identifications" %>

<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Identifications</h1>
    <%= link_to "New identification", new_identification_path, class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
  </div>

  <div id="identifications" class="min-w-full divide-y divide-gray-200 space-y-5">
    <% if @identifications.any? %>
      <% @identifications.each do |identification| %>
        <div class="flex justify-between items-center">
          <%= render identification %>
          <div class="space-x-2">
            <%= link_to "Show", identification, class: "rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= link_to "Edit", edit_identification_path(identification), class: "rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <div class="inline-block">
              <%= button_to "Destroy", identification, method: :delete, class: "rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
            </div>
          </div>
        </div>
      <% end %>
    <% else %>
      <p class="text-center my-10">No identifications found.</p>
    <% end %>
  </div>
</div>

app/views/identifications/new.html.erb
<% content_for :title, "New identification" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New identification</h1>

  <%= render "form", identification: @identification %>

  <%= link_to "Back to identifications", identifications_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/identifications/show.html.erb
<% content_for :title, "Showing identification" %>

<div class="md:w-2/3 w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl">Showing identification</h1>

  <%= render @identification %>

  <%= link_to "Edit this identification", edit_identification_path(@identification), class: "mt-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to identifications", identifications_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <div class="inline-block ml-2">
    <%= button_to "Destroy this identification", @identification, method: :delete, class: "mt-2 rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
  </div>
</div>